// api/github/push-fixes.ts
// POST /api/github/push-fixes
//
// Security design: this endpoint never commits arbitrary client-provided
// paths or content. It accepts only:
//   - repoFullName  — which repo to push to (validated by the user's OAuth token)
//   - approvedIds   — indices into the artifacts array the user approved
//   - artifacts     — the scan artifacts (same payload sent to preview-fixes)
//   - scannedUrl    — for the PR title/body
//
// All file paths and content are DERIVED server-side via computeApprovedFileChanges,
// and every path is validated against ALLOWED_REPO_PATHS before committing.

import express from 'express';
import { findUserByApiKey, getUserGithubToken } from '../../services/dbService';
import {
  computeApprovedFileChanges,
  getDefaultBranch,
  createBranchAndPR,
  ArtifactInput,
} from '../../services/githubPatchService';
import type { ApiError } from '../../types';

function getApiKey(req: express.Request): string | null {
  const h = req.headers.authorization;
  if (!h) return null;
  return (Array.isArray(h) ? h[0] : h)?.split(' ')[1] ?? null;
}

function parseOwnerRepo(fullName: string): { owner: string; repo: string } | null {
  const parts = fullName.split('/');
  if (parts.length !== 2 || !parts[0] || !parts[1]) return null;
  return { owner: parts[0], repo: parts[1] };
}

function buildPrBody(
  files: Array<{ path: string; content: string }>,
  manualItems: Array<{ description: string; snippet: string }>,
  scannedUrl: string,
): string {
  const lines: string[] = [
    `## AI SEO Automated Fixes`,
    ``,
    `These changes were generated by [Rain OS](https://getrainos.com) after scanning **${scannedUrl}**.`,
    ``,
  ];

  if (files.length > 0) {
    lines.push(`### Files Changed`);
    for (const f of files) {
      lines.push(`- **\`${f.path}\`**`);
    }
    lines.push('');
  }

  if (manualItems.length > 0) {
    lines.push(`### Manual Steps Required`);
    lines.push(`The following fixes could not be auto-applied because no HTML template was detected. Copy and paste each snippet into your page's \`<head>\`:`);
    lines.push('');
    for (const item of manualItems) {
      lines.push(`#### ${item.description}`);
      lines.push('```html');
      lines.push(item.snippet);
      lines.push('```');
      lines.push('');
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by Rain OS URL Scanner — [getrainos.com](https://getrainos.com)*`);

  return lines.join('\n');
}

export default async function handler(req: express.Request, res: express.Response) {
  const apiKey = getApiKey(req);
  if (!apiKey) {
    return res.status(401).json({ error: 'unauthorized', message: 'API key missing' } as ApiError);
  }
  const user = await findUserByApiKey(apiKey);
  if (!user) {
    return res.status(401).json({ error: 'unauthorized', message: 'Invalid API key' } as ApiError);
  }
  if (!user.githubId) {
    return res.status(400).json({ error: 'not_connected', message: 'GitHub account not connected.' });
  }

  const { repoFullName, approvedIds, artifacts, scannedUrl } = req.body as {
    repoFullName?: string;
    approvedIds?: string[];
    artifacts?: ArtifactInput[];
    scannedUrl?: string;
  };

  if (!repoFullName) {
    return res.status(400).json({ error: 'bad_request', message: 'repoFullName is required' });
  }
  if (!Array.isArray(approvedIds) || approvedIds.length === 0) {
    return res.status(400).json({ error: 'bad_request', message: 'approvedIds must be a non-empty array' });
  }
  if (!Array.isArray(artifacts) || artifacts.length === 0) {
    return res.status(400).json({ error: 'bad_request', message: 'artifacts array is required' });
  }

  const parsed = parseOwnerRepo(repoFullName);
  if (!parsed) {
    return res.status(400).json({ error: 'bad_request', message: 'Invalid repoFullName — use "owner/repo" format' });
  }

  const rawToken = await getUserGithubToken(user.id);
  if (!rawToken) {
    return res.status(400).json({ error: 'not_connected', message: 'GitHub token not found. Reconnect GitHub in Settings.' });
  }
  const token: string = rawToken;
  const { owner, repo } = parsed;
  const url = scannedUrl ?? 'unknown URL';

  try {
    // Filter the artifact list to only the IDs the user approved.
    // IDs are artifact array indices (strings), so we convert and range-check.
    const approvedSet = new Set(approvedIds);
    const selectedArtifacts = artifacts.filter((_, i) => approvedSet.has(String(i)));

    if (selectedArtifacts.length === 0) {
      return res.status(400).json({ error: 'bad_request', message: 'No valid artifacts matched the approved IDs.' });
    }

    // Derive all file changes server-side — paths and content come from our
    // own logic (computeApprovedFileChanges), not from the client.
    const { files, manualItems } = await computeApprovedFileChanges(
      token, owner, repo, selectedArtifacts,
    );

    if (files.length === 0) {
      return res.status(400).json({
        error: 'no_file_changes',
        message: manualItems.length > 0
          ? 'All selected fixes are manual steps — no files to commit. Copy the snippets from the review panel and apply them to your page <head>.'
          : 'No file changes to commit for the selected fixes.',
      });
    }

    const { branch: baseBranch, sha: baseSha } = await getDefaultBranch(token, owner, repo);
    const branchName = `aiseo-fixes/${Date.now()}`;
    const prTitle = `AI SEO: automated fixes from scan of ${url}`;
    const prBody = buildPrBody(files, manualItems, url);

    const prUrl = await createBranchAndPR({
      token,
      owner,
      repo,
      baseSha,
      baseBranch,
      branchName,
      files,
      prTitle,
      prBody,
    });

    return res.status(200).json({ success: true, prUrl });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Push failed';
    console.error('GitHub push-fixes error:', message);
    if (message.includes('rate limit') || message.includes('403')) {
      return res.status(429).json({ error: 'rate_limit', message: 'GitHub API rate limit reached. Try again later.' });
    }
    if (message.includes('Not Found') || message.includes('404')) {
      return res.status(404).json({ error: 'not_found', message: 'Repository not found or not accessible.' });
    }
    return res.status(500).json({ error: 'internal_server_error', message });
  }
}
