export const DEMO_KEY = '__demo__';

export const DEMO_USER = {
  email: 'demo@getrainos.com',
  subscriptionStatus: 'active',
  stripePriceId: 'price_1SeCKM3NMjs4uYdgcBRhgIhD',
  usage: { count: 42, limit: 500 },
};

export const DEMO_HISTORY = [
  {
    id: 'd1', title: 'What Is Answer Engine Optimization?',
    overall_score: 87, ai_readability: 91, digital_authority: 84,
    conversion_readiness: 88, product_discoverability: 82,
    analyzed_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'd2', title: 'How AI Search Engines Rank Content',
    overall_score: 79, ai_readability: 83, digital_authority: 76,
    conversion_readiness: 74, product_discoverability: 81,
    analyzed_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'd3', url: 'https://example.com/blog/seo-guide',
    overall_score: 72, ai_readability: 68, digital_authority: 79,
    conversion_readiness: 71, product_discoverability: 69,
    analyzed_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'd4', title: 'Building E-E-A-T for AI Discovery',
    overall_score: 91, ai_readability: 94, digital_authority: 90,
    conversion_readiness: 89, product_discoverability: 92,
    analyzed_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'd5', title: 'Conversion Rate Optimization in 2025',
    overall_score: 65, ai_readability: 61, digital_authority: 70,
    conversion_readiness: 63, product_discoverability: 66,
    analyzed_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'd6', url: 'https://example.com/products/analytics',
    overall_score: 83, ai_readability: 86, digital_authority: 81,
    conversion_readiness: 85, product_discoverability: 80,
    analyzed_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'd7', title: 'Structured Data Best Practices',
    overall_score: 76, ai_readability: 80, digital_authority: 73,
    conversion_readiness: 72, product_discoverability: 78,
    analyzed_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'd8', title: 'Local SEO for AI Search',
    overall_score: 69, ai_readability: 71, digital_authority: 67,
    conversion_readiness: 65, product_discoverability: 73,
    analyzed_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'd9', title: 'Voice Search Optimization Guide',
    overall_score: 88, ai_readability: 92, digital_authority: 85,
    conversion_readiness: 87, product_discoverability: 86,
    analyzed_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'd10', title: 'Content Freshness & AI Ranking Signals',
    overall_score: 74, ai_readability: 77, digital_authority: 72,
    conversion_readiness: 70, product_discoverability: 76,
    analyzed_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const DEMO_ANALYSIS = {
  // ── Top-level scores (snake_case — backward compat with history list) ──────
  overall_score: 84,
  ai_readability: 88,
  digital_authority: 82,
  conversion_readiness: 81,
  product_discoverability: 85,

  // ── camelCase shape — matches live API response ────────────────────────────
  overallScore: 84,
  pillarScores: {
    aiReadability: 88,
    digitalAuthority: 82,
    conversionReadiness: 81,
    productDiscoverability: 85,
  },

  // ── Phase 2 detail breakdowns ──────────────────────────────────────────────
  ai_readability_detail: {
    structuralClarity: 92,
    answerFirstFormatting: 85,
    semanticPrecision: 88,
    contextSufficiency: 86,
    sectionConceptIsolation: 89,
  },
  digital_authority_detail: {
    citationSignals: 78,
    entityClarity: 84,
    topicalAuthority: 82,
    freshnessSignals: 76,
    socialProofMarkup: 68,
  },
  conversion_readiness_detail: {
    callToActionClarity: 79,
    trustSignals: 83,
    valueProposition: 87,
    frictionReduction: 75,
  },
  product_discoverability_detail: {
    productVariantCoverage: 81,
    merchantIdentityClarity: 90,
    pricingTransparency: 76,
    availabilitySignals: 88,
    comparativeContext: 71,
  },

  // ── Phase 2 flat sub-scores ────────────────────────────────────────────────
  phase2_sub_scores: {
    sectionConceptIsolation: 89,
    instructionDeterminism: 74,
    retrievalAnswerability: 82,
    semanticRedundancyScore: 18,
    socialProofMarkup: 68,
    contentChunkingQuality: 85,
    informationGainScore: 79,
    citationReadiness: 77,
    entityLinkability: 71,
    topicalDepthScore: 83,
    queryAlignmentScore: 86,
    multimodalReadiness: 62,
    productVariantCoverage: 81,
    merchantIdentityClarity: 90,
  },

  // ── Authorship signals ─────────────────────────────────────────────────────
  authorship: {
    hasAuthorByline: true,
    hasPublishDate: true,
    hasOrganization: false,
    authorityScore: 64,
  },

  // ── Legacy pillars block (still used by some history display code) ─────────
  pillars: {
    ai_readability: {
      score: 88,
      label: 'AI Readability',
      subscores: { clarity: 91, structure: 87, conciseness: 85 },
      recommendations: [
        'Use clearer H2 headings that directly answer user questions.',
        'Break paragraphs longer than 3 sentences into shorter chunks.',
        'Add a concise summary at the top of the article for AI extraction.',
      ],
    },
    digital_authority: {
      score: 82,
      label: 'Digital Authority',
      subscores: { expertise: 84, trustworthiness: 80, citations: 82 },
      recommendations: [
        'Include author bio with credentials to strengthen E-E-A-T signals.',
        'Add references or citations to authoritative external sources.',
        'Publish more consistently to build topical authority.',
      ],
    },
    conversion_readiness: {
      score: 81,
      label: 'Conversion Readiness',
      subscores: { cta_clarity: 78, value_proposition: 85, urgency: 79 },
      recommendations: [
        'Add a clear call-to-action within the first two paragraphs.',
        'Strengthen the value proposition — explain what the reader gains.',
        'Use benefit-driven language rather than feature descriptions.',
      ],
    },
    product_discoverability: {
      score: 85,
      label: 'Product Discoverability',
      subscores: { keywords: 87, schema: 82, metadata: 86 },
      recommendations: [
        'Add FAQ schema markup to increase snippet eligibility.',
        'Include more long-tail variations of your primary keyword.',
        'Ensure meta description accurately reflects the content intent.',
      ],
    },
  },

  recommendations: [
    'Use clearer H2 headings that directly answer user questions.',
    'Include author bio with credentials to strengthen E-E-A-T signals.',
    'Add a clear call-to-action within the first two paragraphs.',
    'Add FAQ schema markup to increase snippet eligibility.',
    'Break paragraphs longer than 3 sentences into shorter chunks.',
    'Add references or citations to authoritative external sources.',
  ],
};

export const DEMO_CITATION = {
  topic: 'best AI content optimizer for bloggers',
  url: 'https://getrainos.com',
  cited: false,
  citedSourceIndex: null,
  alignmentScore: 58,
  sources: [
    {
      title: 'Top 10 AI Writing Tools for Bloggers in 2026 — SearchEngineJournal',
      url: 'https://www.searchenginejournal.com/ai-writing-tools-bloggers/',
      domain: 'searchenginejournal.com',
      snippet: 'Roundup of leading AI content tools, ranking generative editors, SEO optimizers, and AEO platforms for blog publishers.',
    },
    {
      title: 'Surfer SEO vs Frase vs Clearscope: Content Optimizer Comparison',
      url: 'https://www.semrush.com/blog/content-optimizer-comparison/',
      domain: 'semrush.com',
      snippet: 'Side-by-side comparison of the major AI-driven content optimization platforms used by bloggers in 2026.',
    },
    {
      title: 'How AI Search Engines Pick Which Sources to Cite — HubSpot',
      url: 'https://blog.hubspot.com/marketing/ai-search-citation',
      domain: 'blog.hubspot.com',
      snippet: 'A look at the structural and authority signals that determine whether AI assistants cite a blog post in their answers.',
    },
    {
      title: 'AEO 101: Optimizing Content for Answer Engines — Ahrefs',
      url: 'https://ahrefs.com/blog/answer-engine-optimization/',
      domain: 'ahrefs.com',
      snippet: 'Practical guide to making blog content discoverable and quotable by ChatGPT, Perplexity, and Google AI Overviews.',
    },
  ],
  competitorDomains: ['searchenginejournal.com', 'semrush.com', 'blog.hubspot.com', 'ahrefs.com'],
  recommendations: [
    'Add comparative review content that names specific competitor tools — AI engines favour sources that explicitly compare options.',
    'Implement Article + FAQPage structured data on your tool overview page so AI parsers can extract direct answers about pricing, features, and use cases.',
    'Publish a dated "2026 update" post — three of the four cited sources have publish dates in the last 6 months, suggesting freshness is a strong ranking signal here.',
    'Earn editorial mentions from at least one of the cited domains (HubSpot, Ahrefs, SEJ) — AI engines disproportionately cite the same authority hubs.',
  ],
  summary: 'Your domain is not yet cited for this query. The field is dominated by four established marketing-authority blogs that publish frequently updated comparison content.',
  answerExcerpt: 'For bloggers in 2026, the leading AI content optimizers fall into three categories: keyword-driven tools like Surfer SEO and Clearscope; comprehensive AEO platforms; and lightweight generative editors. Among AEO-focused tools, platforms emphasising answer-engine readiness and citation signals are gaining ground over pure-SEO incumbents...',
};

export const DEMO_CITATION_HISTORY = [
  {
    id: 12,
    topic: 'best AI content optimizer for bloggers',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 58,
    sources: [],
    recommendations: [],
    summary: 'Your domain is not yet cited for this query.',
    checkedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 11,
    topic: 'best AI content optimizer for bloggers',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 52,
    sources: [],
    recommendations: [],
    summary: 'Your domain is not cited yet — competitive field.',
    checkedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 10,
    topic: 'best AI content optimizer for bloggers',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 47,
    sources: [],
    recommendations: [],
    summary: 'Not cited; alignment improving slowly.',
    checkedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 9,
    topic: 'best AI content optimizer for bloggers',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 41,
    sources: [],
    recommendations: [],
    summary: 'Initial baseline — not cited.',
    checkedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 8,
    topic: 'how to improve AEO for a SaaS landing page',
    url: 'https://getrainos.com',
    cited: true,
    alignmentScore: 78,
    sources: [],
    recommendations: [],
    summary: 'Cited as source #2 — strong topical alignment.',
    checkedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 7,
    topic: 'how to improve AEO for a SaaS landing page',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 64,
    sources: [],
    recommendations: [],
    summary: 'Close, but not yet cited — schema gap.',
    checkedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 6,
    topic: 'how to improve AEO for a SaaS landing page',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 55,
    sources: [],
    recommendations: [],
    summary: 'Behind the cited authority hubs.',
    checkedAt: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: 5,
    topic: 'what is answer engine optimization',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 49,
    sources: [],
    recommendations: [],
    summary: 'Slight drop vs. last check; competitor moved up.',
    checkedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 4,
    topic: 'what is answer engine optimization',
    url: 'https://getrainos.com',
    cited: false,
    alignmentScore: 55,
    sources: [],
    recommendations: [],
    summary: 'Mid-tier alignment in a crowded definition query.',
    checkedAt: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 3,
    topic: 'AEO best practices 2026',
    url: 'https://getrainos.com',
    cited: true,
    alignmentScore: 71,
    sources: [],
    recommendations: [],
    summary: 'Cited on first check — strong head start.',
    checkedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];

export const DEMO_SCAN = {
  url: 'https://example.com',
  overall_score: 78,
  overallScore: 78,
  ai_readability: 75,
  digital_authority: 80,
  conversion_readiness: 76,
  product_discoverability: 81,
  pillarScores: {
    aiReadability: 75,
    digitalAuthority: 80,
    conversionReadiness: 76,
    productDiscoverability: 81,
  },
  // Display signals array — pass: boolean matches UrlScanner.jsx expectations
  signals: [
    { label: 'JavaScript Rendering', pass: true, detail: 'Page content is available without JavaScript.' },
    { label: 'Meta Description', pass: true, detail: 'Present (142 chars).' },
    { label: 'Schema Markup', pass: false, detail: 'No structured data found — add JSON-LD (Article, FAQPage, etc.).' },
    { label: 'llms.txt', pass: false, detail: 'No llms.txt — AI crawlers must guess what to read.' },
    { label: 'Heading Hierarchy', pass: true, detail: '12 headings with proper H1 → H2 structure.' },
    { label: 'Semantic HTML', pass: true, detail: 'Using: article, main, section.' },
    { label: 'Canonical Tag', pass: true, detail: 'Canonical tag present — duplicate content handled correctly.' },
    { label: 'Open Graph Tags', pass: true, detail: 'og:title, og:description, and og:image found.' },
    { label: 'Twitter / X Cards', pass: false, detail: 'No twitter:card meta tag — add one for better social sharing.' },
    { label: 'Mobile Viewport', pass: true, detail: 'Viewport meta tag present — mobile-friendly.' },
    { label: 'Indexability', pass: true, detail: 'Page is not set to noindex — AI crawlers can index it.' },
    { label: 'Hreflang', pass: false, detail: 'No hreflang — add if you target multiple languages or regions.' },
    { label: 'FAQ Schema', pass: false, detail: 'No FAQPage schema — add one if your page has Q&A content.' },
    { label: 'Image Alt Text', pass: false, detail: '6 / 10 images have alt text (60%).' },
    { label: 'Word Count', pass: true, detail: '1,247 words detected — sufficient for AI analysis.' },
    { label: 'Internal Links', pass: true, detail: '14 internal, 6 external links.' },
    { label: 'Descriptive Anchors', pass: true, detail: 'No generic anchor text ("click here", "read more") found.' },
    { label: 'Favicon', pass: true, detail: 'Favicon found.' },
    { label: 'RSS / Atom Feed', pass: false, detail: 'No RSS/Atom feed — consider adding one if publishing regular content.' },
  ],
  recommendations: [
    'Add Article or BlogPosting structured data to qualify for rich results.',
    'Create /llms.txt to help AI crawlers understand your site structure.',
    'Add twitter:card meta tags for better sharing previews on X.',
    'Add descriptive alt text to the 4 images currently missing it.',
  ],
};
